### ISSUE TITLE
[ 1.6.0-beta9] [Install] Erreur lors de la migration

### ISSUE THREAD

**Issue by Inf3rnus187** [SelMaK-fr/proaxive#1]
Salut, super boulot et première issue ou participation pour moi.

En faisant une fresh install ce soir, j'ai eu cette erreur.

```
vendor/bin/phinx migrate 
Phinx by CakePHP - https://phinx.org.

using config file phinx.yml
using config parser yml
using migration paths 
 - /var/www/html/db/migrations
using seed paths 
 - /var/www/html/db/seeds
warning no environment specified, defaulting to: development
using adapter mysql
using database proaxive
using table prefix pe1x_
ordering by creation time

 == 20211013224125 CreateSocietyModel: migrating
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'address' (max = 21844); use BLOB or TEXT instead in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
Stack trace:
#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('CREATE TABLE `p...')
#1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(339): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `p...')
#2 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#3 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#4 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#5 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TablePrefixAdapter.php(65): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#6 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TablePrefixAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#7 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TablePrefixAdapter))
#8 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions(false)
#9 /var/www/html/db/migrations/20211013224125_create_society_model.php(59): Phinx\Db\Table->create()
#10 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): CreateSocietyModel->change()
#11 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(376): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateSocietyModel), 'up', false)
#12 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration('development', Object(CreateSocietyModel), 'up', false)
#13 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('development', '20211013224125', false)
#14 /var/www/html/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#20 {main}
```

Facile à réparer et venant de '[db/migrations/20211013224125_create_society_model.php](https://github.com/SelMaK-fr/proaxive/blob/f26b16ac08b10ba1b419e8484392c6fc6c1271a0/db/migrations/20211013224125_create_society_model.php#L45)'

A la ligne 45 `            ->addColumn('address', 'string', [`

On remplace string par text et c'est regler.

Je boss sur une petite install via Docker j'essaierai de partager.

**Comment by Inf3rnus187** [comment]
> Salut, super boulot et première issue ou participation pour moi.
> 
> En faisant une fresh install ce soir, j'ai eu cette erreur.
> 
> ```
> vendor/bin/phinx migrate 
> Phinx by CakePHP - https://phinx.org.
> 
> using config file phinx.yml
> using config parser yml
> using migration paths 
>  - /var/www/html/db/migrations
> using seed paths 
>  - /var/www/html/db/seeds
> warning no environment specified, defaulting to: development
> using adapter mysql
> using database proaxive
> using table prefix pe1x_
> ordering by creation time
> 
>  == 20211013224125 CreateSocietyModel: migrating
> PDOException: SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'address' (max = 21844); use BLOB or TEXT instead in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
> Stack trace:
> #0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('CREATE TABLE `p...')
> #1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(339): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `p...')
> #2 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
> #3 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(113): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
> #4 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(356): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
> #5 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TablePrefixAdapter.php(65): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
> #6 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(146): Phinx\Db\Adapter\TablePrefixAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
> #7 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TablePrefixAdapter))
> #8 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(611): Phinx\Db\Table->executeActions(false)
> #9 /var/www/html/db/migrations/20211013224125_create_society_model.php(59): Phinx\Db\Table->create()
> #10 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): CreateSocietyModel->change()
> #11 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(376): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateSocietyModel), 'up', false)
> #12 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration('development', Object(CreateSocietyModel), 'up', false)
> #13 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('development', '20211013224125', false)
> #14 /var/www/html/vendor/symfony/console/Command/Command.php(298): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 /var/www/html/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #16 /var/www/html/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #17 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #18 /var/www/html/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #19 /var/www/html/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
> #20 {main}
> ```
> 
> Facile à réparer et venant de '[db/migrations/20211013224125_create_society_model.php](https://github.com/SelMaK-fr/proaxive/blob/f26b16ac08b10ba1b419e8484392c6fc6c1271a0/db/migrations/20211013224125_create_society_model.php#L45)'
> 
> A la ligne 45 ` ->addColumn('address', 'string', [`
> 
> On remplace string par text et c'est regler.
> 
> Je boss sur une petite install via Docker j'essaierai de partager.

**Comment by SelMaK-fr** [comment]
Bonjour @Inf3rnus187 
Ca sera corrigé sur la beta10. Merci pour ton retour :)
